apiVersion: model.hydra.io/v1alpha1
kind: ModelSpec
metadata:
  name: minimax-text-01
spec:
  deployments:
  - customRuntimeArgs: []
    resourceRequirements:
      cpu: 8
      gpuCount: 8
      gpuType: gpu
      memory: 640
      perGPUMemoryGB: 80
    runtime: vllm
    versionRequired: '>=v0.6.4'
  descriptor:
    description:
      enUS: MiniMax-Text-01 is a powerful language model with 456 billion total parameters,
        of which 45.9 billion are activated per token.
      zhCN: MiniMax-Text-01 是一个强大的语言模型，共有 4560 亿个参数，其中每个 token 激活 459 亿个参数。
    display: MiniMax-Text-01
    icon:
      src: https://public-resources.d.run/models/logos/minimax-logo.webp
      type: image/svg
    links:
    - description: About
      url: https://www.minimaxi.com/
    provider:
      id: minimax
      name:
        enUS: MiniMax
        zhCN: 稀宇科技
    tags:
    - TEXT_GENERATION
  source:
    huggingface:
      name: MiniMaxAI/MiniMax-Text-01
    modelscope:
      name: MiniMaxAI/MiniMax-Text-01
