apiVersion: model.hydra.io/v1alpha1
kind: ModelSpec
metadata:
  name: qwen2-0.5b-instruct
spec:
  config:
    maxTokens: 4096
  deployments:
  - customRuntimeArgs: []
    resourceRequirements:
      cpu: 4
      gpuCount: 1
      gpuType: vgpu
      memory: 8
      perGPUMemoryGB: 5
    runtime: vllm
    versionRequired: '>=v0.6.5'
  - customRuntimeArgs: []
    resourceRequirements:
      cpu: 4
      gpuCount: 1
      gpuType: metax-gpu
      memory: 8
      perGPUMemoryGB: 5
    runtime: vllm
    versionRequired: '>=v0.6.5'
  - customRuntimeArgs: []
    resourceRequirements:
      cpu: 8
      gpuCount: 0
      gpuType: cpu
      memory: 32
      perGPUMemoryGB: 0
    runtime: vllm
    versionRequired: '>=v0.6.5'
  descriptor:
    description:
      enUS: A 0.5B parameter instruction-tuned model from the Qwen2 series, suitable
        for multilingual text generation and understanding.
      zhCN: Qwen2 系列的 0.5B 参数指令微调模型，适用于多语言文本生成和理解。
    display: Qwen2-0.5B-Instruct
    icon:
      src: https://public-resources.d.run/models/logos/qwen-model-logo.svg
      type: image/svg
    links:
    - description: About
      url: https://github.com/QwenLM
    provider:
      id: alibaba
      name:
        enUS: Alibaba
        zhCN: 通义千问
    tags:
    - TEXT_GENERATION
  source:
    huggingface:
      name: Qwen/Qwen2-0.5B-Instruct
    modelscope:
      name: Qwen/Qwen2-0.5B-Instruct
