apiVersion: model.hydra.io/v1alpha1
kind: ModelSpec
metadata:
  name: deepseek-v3
spec:
  deployments:
  - customRuntimeArgs: []
    resourceRequirements:
      cpu: 8
      gpuCount: 8
      gpuType: nvidia-gpu
      memory: 640
      perGPUMemoryGB: 80
    runtime: vllm
    versionRequired: '>=v0.6.5'
  descriptor:
    description:
      enUS: DeepSeek-V3 is a 671B parameter Mixture-of-Experts language model, activating
        37B parameters per token, trained on 14.8 trillion tokens for advanced language
        understanding.
      zhCN: DeepSeek-V3 是一个拥有 6710 亿参数的专家混合语言模型，每个 token 激活 370 亿参数，在 14.8 万亿个 token
        上训练，具备高级语言理解能力。
    display: 🔥 DeepSeek-V3-0324
    icon:
      src: https://public-resources.d.run/models/logos/deepseek-model-logo.svg
      type: image/svg
    links:
    - description: About
      url: https://www.deepseek.com/
    provider:
      id: deepseek
      name:
        enUS: DeepSeek
        zhCN: 深度求索
    tags:
    - TEXT_GENERATION
  source:
    huggingface:
      name: deepseek-ai/DeepSeek-V3
    modelscope:
      name: deepseek-ai/DeepSeek-V3
