apiVersion: model.hydra.io/v1alpha1
kind: ModelSpec
metadata:
  name: phi-3.5-mini-instruct
spec:
  config:
    maxTokens: 131072
  deployments:
  - customRuntimeArgs:
    - --max-model-len=4096
    resourceRequirements:
      cpu: 4
      gpuCount: 1
      gpuType: vgpu
      memory: 16
      perGPUMemoryGB: 25
    runtime: vllm
    versionRequired: '>=v0.6.5'
  descriptor:
    description:
      enUS: A mini instruction-tuned model from the Phi series, lightweight and suitable
        for various natural language processing tasks.
      zhCN: Phi 系列的迷你指令模型，轻量级设计，适用于多种自然语言处理任务。
    display: Phi-3.5-mini-instruct
    icon:
      src: https://public-resources.d.run/models/logos/phi-model-logo.svg
      type: image/svg
    links:
    - description: About
      url: https://www.microsoft.com/en-us/research/
    provider:
      id: microsoft
      name:
        enUS: Microsoft
        zhCN: 微软
    tags:
    - TEXT_GENERATION
  source:
    huggingface:
      name: microsoft/phi-3.5-mini-instruct
    modelscope:
      name: LLM-Research/Phi-3.5-mini-instruct
