apiVersion: model.hydra.io/v1alpha1
kind: ModelSpec
metadata:
  name: deepseek-r1
spec:
  config:
    maxTokens: 16384
  deployments:
  - customRuntimeArgs: []
    resourceRequirements:
      cpu: 8
      gpuCount: 12
      gpuType: gpu
      memory: 960
      perGPUMemoryGB: 80
    runtime: vllm
    versionRequired: '>=v0.6.5'
  descriptor:
    description:
      enUS: DeepSeek-R1 is an inference model developed by DeepSeek, which uses reinforcement
        learning for post-training, aiming to enhance its inference capabilities,
        especially in complex tasks such as mathematics, coding, and natural language
        reasoning.
      zhCN: DeepSeek-R1，是幻方量化旗下AI公司深度求索（DeepSeek）研发的推理模型。DeepSeek-R1采用强化学习进行后训练，旨在提升推理能力，尤其擅长数学、代码和自然语言推理等复杂任务。
    display: '🔥 DeepSeek-R1 '
    icon:
      src: https://public-resources.d.run/models/logos/deepseek-model-logo.svg
      type: image/svg
    links:
    - description: About
      url: https://www.deepseek.com/
    provider:
      id: deepseek
      name:
        enUS: DeepSeek
        zhCN: 深度求索
    tags:
    - TEXT_GENERATION
  source:
    huggingface:
      name: deepseek-ai/DeepSeek-R1
    modelscope:
      name: deepseek-ai/DeepSeek-R1
