apiVersion: model.hydra.io/v1alpha1
kind: ModelSpec
metadata:
  name: glm-4-9b-chat
spec:
  config:
    maxTokens: 128000
  deployments:
  - customRuntimeArgs:
      - --max-num-batched-tokens=32768 # Reduce maxTokens from 128k to 32k to fit 50GB GPU and avoid OOM
      - --max-model-len=32768          # Align max-model-len with max-num-batched-tokens for stable inference
    resourceRequirements:
      cpu: 4
      gpuCount: 1
      gpuType: vgpu
      memory: 16
      perGPUMemoryGB: 50
    runtime: vllm
    versionRequired: '>=v0.6.5'
  descriptor:
    description:
      enUS: A 9B parameter chat model from the GLM-4 series, optimized for dialogue
        generation and natural language understanding.
      zhCN: GLM-4 系列的9B参数聊天模型，优化用于对话生成和自然语言理解。
    display: glm-4-9b-chat
    icon:
      src: https://public-resources.d.run/models/logos/glm-model-logo.png
      type: image/svg
    links:
    - description: About
      url: https://www.zhipu.ai
    provider:
      id: zhipuai
      name:
        enUS: ZhipuAI
        zhCN: 智谱AI
    tags:
    - TEXT_GENERATION
  source:
    huggingface:
      name: THUDM/glm-4-9b-chat
    modelscope:
      name: ZhipuAI/glm-4-9b-chat
