apiVersion: model.hydra.io/v1alpha1
kind: ModelSpec
metadata:
  name: qwen2.5-coder-32b-instruct
spec:
  config:
    maxTokens: 32768
  deployments:
  - customRuntimeArgs:
      - --enable-auto-tool-choice
      - --tool-call-parser
      - hermes
    resourceRequirements:
      cpu: 1
      gpuCount: 2
      gpuType: vgpu
      memory: 16
      perGPUMemoryGB: 50
    runtime: vllm
    versionRequired: '>=v0.6.5'
  descriptor:
    description:
      enUS: A 32B parameter coder instruction-tuned model from the Qwen2.5 series,
        optimized for code generation and understanding.
      zhCN: Qwen2.5 系列的 32B 参数编码指令模型，专为代码生成和理解优化。
    display: Qwen2.5-Coder-32B-Instruct
    icon:
      src: https://public-resources.d.run/models/logos/qwen-model-logo.svg
      type: image/svg
    links:
    - description: About
      url: https://github.com/QwenLM
    provider:
      id: alibaba
      name:
        enUS: Alibaba
        zhCN: 通义千问
    tags:
    - TEXT_GENERATION
    - TOOLS
  source:
    huggingface:
      name: Qwen/Qwen2.5-Coder-32B-Instruct
    modelscope:
      name: Qwen/Qwen2.5-Coder-32B-Instruct
