apiVersion: model.hydra.io/v1alpha1
kind: ModelSpec
metadata:
  name: deepseek-r1-distill-qwen-14b
spec:
  deployments:
  - customRuntimeArgs:
    - --max-model-len=32768
    - --enforce-eager
    - --enable_reasoning
    - --reasoning_parser=deepseek_r1
    resourceRequirements:
      cpu: 1
      gpuCount: 1
      gpuType: nvidia-vgpu
      memory: 16
      perGPUMemoryGB: 50
    runtime: vllm
    versionRequired: '>=v0.7.1'
  descriptor:
    description:
      enUS: A Qwen-14B distilled model from the DeepSeek series, optimized for efficient
        inference and performance.
      zhCN: DeepSeek 系列基于Qwen-14B的蒸馏模型
    display: Deepseek-R1-Distill-Qwen-14B
    icon:
      src: https://public-resources.d.run/models/logos/deepseek-model-logo.svg
      type: image/svg
    links:
    - description: About
      url: https://www.deepseek.com/
    provider:
      id: deepseek
      name:
        enUS: DeepSeek
        zhCN: DeepSeek
    tags:
    - TEXT_GENERATION
  source:
    huggingface:
      name: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
    modelscope:
      name: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
