apiVersion: model.hydra.io/v1alpha1
kind: ModelSpec
metadata:
  name: qwen2.5-7b-instruct
spec:
  deployments:
  - customRuntimeArgs: []
    resourceRequirements:
      cpu: 1
      gpuCount: 1
      gpuType: nvidia-vgpu
      memory: 16
      perGPUMemoryGB: 25
    runtime: vllm
    versionRequired: '>=v0.6.5'
  descriptor:
    description:
      enUS: A 7B parameter instruction-tuned model from the Qwen2.5 series, supporting
        multiple languages, excelling in long text generation and structured data
        understanding.
      zhCN: Qwen2.5 系列的7B参数指令微调模型，支持多语言，擅长长文本生成和结构化数据理解。
    display: Qwen2.5-7B-Instruct
    icon:
      src: https://public-resources.d.run/models/logos/qwen-model-logo.svg
      type: image/svg
    links:
    - description: About
      url: https://github.com/QwenLM
    provider:
      id: alibaba
      name:
        enUS: Alibaba
        zhCN: 通义千问
    tags:
    - TEXT_GENERATION
  source:
    huggingface:
      name: Qwen/Qwen2.5-VL-7B-Instruct
    modelscope:
      name: Qwen/Qwen2.5-VL-7B-Instruct
