apiVersion: model.hydra.io/v1alpha1
kind: ModelSpec
metadata:
  name: qwen2.5-14b-instruct
spec:
  config:
    maxTokens: 131072
  deployments:
  - customRuntimeArgs: []
    resourceRequirements:
      cpu: 1
      gpuCount: 1
      gpuType: vgpu
      memory: 16
      perGPUMemoryGB: 50
    runtime: vllm
    versionRequired: '>=v0.6.5'
  descriptor:
    description:
      enUS: A 14B parameter instruction-tuned model from the Qwen2.5 series, excelling
        in various tasks, especially coding and mathematics.
      zhCN: Qwen2.5 系列的 14B 参数指令微调模型，在多任务中表现优异，特别是编码和数学能力。
    display: Qwen2.5-14B-Instruct
    icon:
      src: https://public-resources.d.run/models/logos/qwen-model-logo.svg
      type: image/svg
    links:
    - description: About
      url: https://github.com/QwenLM
    provider:
      id: alibaba
      name:
        enUS: Alibaba
        zhCN: 通义千问
    tags:
    - TEXT_GENERATION
    - TOOLS
  source:
    huggingface:
      name: Qwen/Qwen2.5-14B-Instruct
    modelscope:
      name: Qwen/Qwen2.5-14B-Instruct
