name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PyYAML
      run: pip install pyyaml

    - name: Merge YAML files
      run: |
        mkdir -p merged
        python -c "
import os
import yaml

output_file = 'merged/index.yaml'
os.makedirs(os.path.dirname(output_file), exist_ok=True)

merged_data = {}
for root, _, files in os.walk('models'):
    for file in files:
        if file.endswith('.yaml'):
            with open(os.path.join(root, file), 'r') as f:
                data = yaml.safe_load(f)
                merged_data.update(data)

with open(output_file, 'w') as f:
    yaml.dump(merged_data, f)
"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload index.yaml to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: merged/index.yaml
        asset_name: index.yaml
        asset_content_type: application/x-yaml